### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by celabi** [zjhuang22/maskscoring_rcnn#24]
I used the script "python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_net.py --config-file "maskscoring_rcnn/configs/e2e_ms_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 2" to run the code twice. But in the second try I got an error: UnbondLocalError:local variable 'iteration' referenced before assignment.

**Comment by zjhuang22** [comment]
I reproduce your error. The solutions can be: 1. clear the dir "models". There should not be last_checkpoint or *.pth in the dir "models". 2. You may have saved a trained model in the dir "models", and when you run again, the iteration is the same as the *.pth checkpoint. So, in order to avoid this problem, you can set a large SOLVER.MAX_ITER

**Comment by celabi** [comment]
Thank you.
